import dashboardIcon from "../assets/img/dashboard.svg";
import orderIcon from "../assets/img/order.svg";
import customerIcon from "../assets/img/user.svg";
import websiteIcon from "../assets/img/website.svg";
import orders from "../assets/img/ordergraph.png";
import stock from "../assets/img/stocks.png";
import bounce from "../assets/img/bounce.png";

export const sideMenu = [
  {
    id: 1,
    name: "Dashboard",
    icon: dashboardIcon,
    path: "/",
  },
  {
    id: 2,
    name: "Orders",
    icon: orderIcon,
    path: "/orders",
  },

  {
    id: 3,
    name: "Customers",
    icon: customerIcon,
    path: "/customer",
  },
  {
    id: 4,
    name: "Webstie",
    icon: websiteIcon,
    path: "/website",
  },
];

export const cardsData = [
  {
    id: 1,
    name: "Orders",
    icon: orderIcon,
    data: 3846,
    img: orders,
  },
  {
    id: 2,
    name: "Sold Stock",
    icon: orderIcon,
    data: 2648,
    img: stock,
  },
  {
    id: 3,
    name: "Bounce Rate",
    icon: customerIcon,
    per: 15,
    img: bounce,
  },
  {
    id: 4,
    name: "Total Websites",
    icon: websiteIcon,
    data: 349,
  },
  {
    id: 5,
    name: "Live Websites",
    icon: websiteIcon,
    data: 312,
  },
  {
    id: 6,
    name: "Dummy1",
    icon: websiteIcon,
    data: null,
  },
  {
    id: 7,
    name: "Dummy2",
    icon: websiteIcon,
    data: null,
  },
];
export const products = [
  {
    name: "Oxycodon HCI 40 MG (1 Tablet)",
    unitsSold: 3612,
    price: 900567,
    imageUrl:
      "https://tajpharma.in/wp-content/uploads/Oxycodone_Hydrochloride_ER-_Tablet_40mg_Suppliers-scaled.jpg",
  },
  {
    name: "Pregabaline 300 MG 3*15 (45 Capsules) Lyrica",
    unitsSold: 4429,
    price: 870345,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/12/371928408/NG/PW/UF/109604861/pregabalin-300-mg-capsule-1000x1000.jpeg",
  },
  {
    name: "Tramadol 50 MG (30 Tabletten)",
    unitsSold: 3812,
    price: 120567,
    imageUrl:
      "https://bernofarm.com/wp-content/uploads/2021/12/TRAMADOL-50-mg-KAPSUL-depan.png",
  },
  {
    name: "Xanax 1 MG 2*15 (30 Tabletten)",
    unitsSold: 4612,
    price: 91121,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/7/325484280/YG/CF/XB/189532561/18-jpeg-1000x1000.jpeg",
  },
  {
    name: "Zopiclon 7.5MG (30 Tabletten)",
    unitsSold: 2812,
    price: 57599,
    imageUrl:
      "https://tiimg.tistatic.com/fp/1/006/141/zopiclone-tablets-bp-7-5mg-059.jpg",
  },
  // Unique Products with Randomly Assigned Images
  {
    name: "Oxycodon HCI 40 MG (2 Tablets)",
    unitsSold: 3000,
    price: 1801120,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/12/371928408/NG/PW/UF/109604861/pregabalin-300-mg-capsule-1000x1000.jpeg",
  },
  {
    name: "Pregabaline 300 MG 5*15 (75 Capsules) Lyrica",
    unitsSold: 2500,
    price: 1304567,
    imageUrl:
      "https://tiimg.tistatic.com/fp/1/006/141/zopiclone-tablets-bp-7-5mg-059.jpg",
  },
  {
    name: "Tramadol 50 MG (60 Tabletten)",
    unitsSold: 4000,
    price: 450567,
    imageUrl:
      "https://tajpharma.in/wp-content/uploads/Oxycodone_Hydrochloride_ER-_Tablet_40mg_Suppliers-scaled.jpg",
  },
  {
    name: "Xanax 1 MG 1*15 (15 Tabletten)",
    unitsSold: 2000,
    price: 60000,
    imageUrl:
      "https://bernofarm.com/wp-content/uploads/2021/12/TRAMADOL-50-mg-KAPSUL-depan.png",
  },
  {
    name: "Zopiclon 10MG (30 Tabletten)",
    unitsSold: 3500,
    price: 80000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/7/325484280/YG/CF/XB/189532561/18-jpeg-1000x1000.jpeg",
  },
  {
    name: "Oxycodon HCI 80 MG (1 Tablet)",
    unitsSold: 2100,
    price: 1600567,
    imageUrl:
      "https://tiimg.tistatic.com/fp/1/006/141/zopiclone-tablets-bp-7-5mg-059.jpg",
  },
  {
    name: "Pregabaline 150 MG 1*15 (15 Capsules) Lyrica",
    unitsSold: 4700,
    price: 950000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/12/371928408/NG/PW/UF/109604861/pregabalin-300-mg-capsule-1000x1000.jpeg",
  },
  {
    name: "Tramadol 100 MG (20 Tabletten)",
    unitsSold: 1500,
    price: 230000,
    imageUrl:
      "https://tajpharma.in/wp-content/uploads/Oxycodone_Hydrochloride_ER-_Tablet_40mg_Suppliers-scaled.jpg",
  },
  {
    name: "Xanax 2 MG 2*15 (30 Tabletten)",
    unitsSold: 3300,
    price: 45000,
    imageUrl:
      "https://bernofarm.com/wp-content/uploads/2021/12/TRAMADOL-50-mg-KAPSUL-depan.png",
  },
  {
    name: "Zopiclon 15MG (30 Tabletten)",
    unitsSold: 4100,
    price: 65000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/7/325484280/YG/CF/XB/189532561/18-jpeg-1000x1000.jpeg",
  },
  {
    name: "Oxycodon HCI 20 MG (5 Tablets)",
    unitsSold: 5200,
    price: 90000,
    imageUrl:
      "https://tajpharma.in/wp-content/uploads/Oxycodone_Hydrochloride_ER-_Tablet_40mg_Suppliers-scaled.jpg",
  },
  {
    name: "Pregabaline 75 MG 1*15 (15 Capsules)",
    unitsSold: 3400,
    price: 560000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/12/371928408/NG/PW/UF/109604861/pregabalin-300-mg-capsule-1000x1000.jpeg",
  },
  {
    name: "Tramadol 200 MG (10 Tabletten)",
    unitsSold: 2100,
    price: 180000,
    imageUrl:
      "https://bernofarm.com/wp-content/uploads/2021/12/TRAMADOL-50-mg-KAPSUL-depan.png",
  },
  {
    name: "Xanax 3 MG (30 Tabletten)",
    unitsSold: 5000,
    price: 72000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/7/325484280/YG/CF/XB/189532561/18-jpeg-1000x1000.jpeg",
  },
  {
    name: "Zopiclon 5MG (30 Tabletten)",
    unitsSold: 4000,
    price: 45000,
    imageUrl:
      "https://tiimg.tistatic.com/fp/1/006/141/zopiclone-tablets-bp-7-5mg-059.jpg",
  },
  {
    name: "Oxycodon HCI 40 MG (3 Tablets)",
    unitsSold: 1800,
    price: 2700000,
    imageUrl:
      "https://tajpharma.in/wp-content/uploads/Oxycodone_Hydrochloride_ER-_Tablet_40mg_Suppliers-scaled.jpg",
  },
  {
    name: "Pregabaline 500 MG 3*15 (45 Capsules) Lyrica",
    unitsSold: 2200,
    price: 950000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/12/371928408/NG/PW/UF/109604861/pregabalin-300-mg-capsule-1000x1000.jpeg",
  },
  {
    name: "Tramadol 150 MG (15 Tabletten)",
    unitsSold: 2800,
    price: 120567,
    imageUrl:
      "https://bernofarm.com/wp-content/uploads/2021/12/TRAMADOL-50-mg-KAPSUL-depan.png",
  },
  {
    name: "Xanax 2 MG 1*15 (15 Tabletten)",
    unitsSold: 2100,
    price: 45000,
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2023/7/325484280/YG/CF/XB/189532561/18-jpeg-1000x1000.jpeg",
  },
];

export const TargetCountries = [
  "Faroe Islands",
  "Isle of Man",
  "Andorra",
  "Spain",
  "Poland",
  "Ukraine",
  "Germany",
  "United Kingdom",
  "France",
  "Italy",
  "Serbia",
  "Belarus",
  "Romania",
  "Croatia",
  "Slovenia",
  "Austria",
  "Czechia",
  "Switzerland",
  "Greece",
  "North Macedonia",
  "Hungary",
  "Slovakia",
  "Bulgaria",
  "Moldova",
  "Kosovo",
  "Bosnia and Herzegovina",
  "Montenegro",
  "Albania",
  "Norway",
  "Sweden",
  "Finland",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Denmark",
  "Netherlands",
  "Ireland",
  "Iceland",
  "Portugal",
  "Canary Islands",
  "Corsica",
  "Sicily",
  "Balearic Islands",
  "Palermo", // Add specific islands if needed
];

// // transaction data
// export const Transaction = [
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Deli Station Creations",
//     Name: "Robert Fox",
//     Country: "Viet Nam",
//     Level: "Bronze",
//     Time: 1730376872,
//     Paid: "5 mins ago",
//     flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Blueberry天山翡翅",
//     Name: "Alice Smith",
//     Country: "Viet Nam",
//     Level: "Silver",
//     Time: 1730376842,
//     Paid: "10 mins ago",
//     flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Long Biên",
//     Name: "John Doe",
//     Country: "Israel",
//     Level: "Bronze",
//     Time: 1730372872,
//     Paid: "15 mins ago",
//     flag: "https://www.mrflag.com/wp-content/uploads/2018/11/Israel.png",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Everyday Savings",
//     Name: "Sophie Reed",
//     Country: "Russian Federation",
//     Level: "Gold",
//     Paid: "14 hrs ago",
//     Time: 1730372872,
//     flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/800px-Flag_of_Russia.svg.png?20120812153731",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Smart Spender's",
//     Name: "Carter Lee",
//     Country: "Viet Nam",
//     Level: "Silver",
//     Time: 1730375872,
//     Paid: "14 hrs ago",
//     flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Value Village",
//     Name: "Luna Hall",
//     Country: "Brazil",
//     Level: "Bronze",
//     Time: 1730376472,
//     Paid: "14 hrs ago",
//     flag: "https://www.nationalflags.shop/WebRoot/vilkasfi01/Shops/2014080403/53E6/2F4E/F123/7D8D/CCB0/0A28/100B/04B4/Flag_of_Brazil.png",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Discount Darling",
//     Name: "Eli Young",
//     Country: "Australia",
//     Level: "Gold",
//     Time: 1730376870,
//     Paid: "15 hrs ago",
//     flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1920px-Flag_of_Australia_%28converted%29.svg.png",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Bargain Bonanza",
//     Name: "Ava Thompson",
//     Country: "Germany",
//     Level: "Silver",
//     Time: 1730372362,
//     Paid: "15 hrs ago",
//     flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/800px-Flag_of_Russia.svg.png?20120812153731",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Market Place",
//     Name: "Andrew Scott",
//     Country: "France",
//     Level: "Bronze",
//     Time: 1730372252,
//     Paid: "15 hrs ago",
//     flag: "https://www.nationalflags.shop/WebRoot/vilkasfi01/Shops/2014080403/53E6/2F4E/F123/7D8D/CCB0/0A28/100B/04B4/Flag_of_Brazil.png",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Fresh Mart",
//     Name: "Ella Carter",
//     Country: "Japan",
//     Level: "Gold",
//     Time: 1730372852,
//     Paid: "16 hrs ago",
//     flag: "https://www.nationalflags.shop/WebRoot/vilkasfi01/Shops/2014080403/53E6/2F4E/F123/7D8D/CCB0/0A28/100B/04B4/Flag_of_Brazil.png",
//   },
//   {
//     imgUrl:
//       "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
//     Store_Name: "Grocery Hub",
//     Name: "Zachary Campbell",
//     Country: "South Africa",
//     Level: "Silver",
//     Time: 1730372352,
//     Paid: "16 hrs ago",
//     flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
//   },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Daisy Reed",
//   //   Country: "India",
//   //   Level: "Bronze",
//   //   Time: 1730376572,
//   //   Paid: "16 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Caleb Turner",
//   //   Country: "China",
//   //   Level: "Gold",
//   //   Time: 1730376832,
//   //   Paid: "17 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Julia Lewis",
//   //   Country: "United Kingdom",
//   //   Level: "Silver",
//   //   Time: 1730349872,
//   //   Paid: "17 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Avery Perez",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 17303246872,
//   //   Paid: "17 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Liam Morgan",
//   //   Country: "Saudi Arabia",
//   //   Level: "Gold",
//   //   Time: 17307676872,
//   //   Paid: "18 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Olivia Rogers",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Silver",
//   //   Time: 173037246872,
//   //   Paid: "18 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Isaac Sanchez",
//   //   Country: "Russian Federation",
//   //   Level: "Bronze",
//   //   Time: 1730324872,
//   //   Paid: "18 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Emily Perez",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "19 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Benjamin Martinez",
//   //   Country: "Brazil",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "19 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Sofia Collins",
//   //   Country: "Australia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "19 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Oliver Young",
//   //   Country: "Germany",
//   //   Level: "Gold",
//   //   Time: 1730396872,
//   //   Paid: "20 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Madison Hughes",
//   //   Country: "France",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "20 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "David Anderson",
//   //   Country: "Japan",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "20 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Ava Green",
//   //   Country: "South Africa",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "21 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Lucas Johnson",
//   //   Country: "India",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "21 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Mia Brown",
//   //   Country: "China",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "21 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Jackson White",
//   //   Country: "United Kingdom",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "22 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Amelia Thomas",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "22 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Ethan Clark",
//   //   Country: "Saudi Arabia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "22 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Scarlett Lewis",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "23 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Henry Walker",
//   //   Country: "Russian Federation",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "23 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Zoe Hill",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "23 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Daniel Lee",
//   //   Country: "Brazil",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "24 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Sophie Taylor",
//   //   Country: "Australia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "24 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Elijah Moore",
//   //   Country: "Germany",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "24 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Mila Jackson",
//   //   Country: "France",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "25 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Jacob Smith",
//   //   Country: "Japan",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "25 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Sophia Rodriguez",
//   //   Country: "South Africa",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "25 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "William Walker",
//   //   Country: "India",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "26 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Abigail Young",
//   //   Country: "China",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "26 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "James Martinez",
//   //   Country: "United Kingdom",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "26 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Ella Hall",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "27 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Alexander Rodriguez",
//   //   Country: "Saudi Arabia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "27 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Victoria Clark",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "27 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Samuel Nelson",
//   //   Country: "Russian Federation",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "28 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Chloe Allen",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "28 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Michael Scott",
//   //   Country: "Brazil",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "28 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Layla Carter",
//   //   Country: "Australia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "29 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Benjamin Lewis",
//   //   Country: "Germany",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "29 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Grace Baker",
//   //   Country: "France",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "29 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Nora Turner",
//   //   Country: "Japan",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "30 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Gabriel Hall",
//   //   Country: "South Africa",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "30 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Ava Young",
//   //   Country: "India",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "30 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Oliver Lee",
//   //   Country: "China",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "31 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Sophia Davis",
//   //   Country: "United Kingdom",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "31 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Noah Clark",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "31 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Sophie Rodriguez",
//   //   Country: "Saudi Arabia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "32 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Mason Evans",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "32 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Charlotte Parker",
//   //   Country: "Russian Federation",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "32 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Lucas Scott",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "33 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Isabella Moore",
//   //   Country: "Brazil",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "33 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Anthony White",
//   //   Country: "Australia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "33 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Harper Hill",
//   //   Country: "Germany",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "34 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Liam Brown",
//   //   Country: "France",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "34 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Ava Harris",
//   //   Country: "Japan",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "34 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Jackson White",
//   //   Country: "South Africa",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "35 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Amelia Davis",
//   //   Country: "India",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "35 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Nathan Carter",
//   //   Country: "China",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "35 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Gabriel Lopez",
//   //   Country: "United Kingdom",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "36 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Layla Scott",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "36 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Elena Turner",
//   //   Country: "Saudi Arabia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "36 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Matthew Hall",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "37 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Charlotte Moore",
//   //   Country: "Russian Federation",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "37 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Dylan Robinson",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "37 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Mia Hall",
//   //   Country: "Brazil",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "38 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Isabella Young",
//   //   Country: "Australia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "38 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Ryan Rodriguez",
//   //   Country: "Germany",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "38 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Zoe Young",
//   //   Country: "France",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "39 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Lucas Martinez",
//   //   Country: "Japan",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "39 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Ella Brown",
//   //   Country: "South Africa",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "39 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Aiden Clark",
//   //   Country: "India",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "40 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Natalie Hall",
//   //   Country: "China",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "40 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Zachary Wilson",
//   //   Country: "United Kingdom",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "40 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Sophia Thomas",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "41 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Jacob Walker",
//   //   Country: "Saudi Arabia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "41 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Grace Thompson",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "41 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Emily Lee",
//   //   Country: "Russian Federation",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "42 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Evelyn Martinez",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "42 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Michael Wilson",
//   //   Country: "Brazil",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "42 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Isabella Johnson",
//   //   Country: "Australia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "43 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "William Harris",
//   //   Country: "Germany",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "43 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Lucas Johnson",
//   //   Country: "France",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "43 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Liam Garcia",
//   //   Country: "Japan",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "44 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Olivia Lee",
//   //   Country: "South Africa",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "44 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "David Martinez",
//   //   Country: "India",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "44 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Abigail Brown",
//   //   Country: "China",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "45 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Joshua White",
//   //   Country: "United Kingdom",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "45 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Emily Thompson",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "45 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Chloe Johnson",
//   //   Country: "Saudi Arabia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "46 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Henry Lee",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "46 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Lily Thompson",
//   //   Country: "Russian Federation",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "46 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Isabella Wilson",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "47 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Eli Davis",
//   //   Country: "Brazil",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "47 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Lucas Clark",
//   //   Country: "Australia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "47 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Abigail Young",
//   //   Country: "Germany",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "48 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Elijah White",
//   //   Country: "France",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "48 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Ella Harris",
//   //   Country: "Japan",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "48 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Matthew Scott",
//   //   Country: "South Africa",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "49 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Ava Wilson",
//   //   Country: "India",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "49 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "James Johnson",
//   //   Country: "China",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "49 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Olivia Miller",
//   //   Country: "United Kingdom",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "50 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Henry Brown",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "50 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Aiden Lopez",
//   //   Country: "Saudi Arabia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "50 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Mia Young",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "51 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Chloe Thomas",
//   //   Country: "Russian Federation",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "51 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Alexander Young",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "51 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Sophia Clark",
//   //   Country: "Brazil",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "52 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Mason Harris",
//   //   Country: "Australia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "52 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Evelyn Walker",
//   //   Country: "Germany",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "52 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Isabella Allen",
//   //   Country: "France",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "53 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "James Johnson",
//   //   Country: "Japan",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "53 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Charlotte Scott",
//   //   Country: "South Africa",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "53 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Daniel Taylor",
//   //   Country: "India",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "54 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Olivia Young",
//   //   Country: "China",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "54 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Samuel Wilson",
//   //   Country: "United Kingdom",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "54 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Isabella Brown",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "55 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Gabriel Johnson",
//   //   Country: "Saudi Arabia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "55 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Emily Lewis",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "55 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Ethan Davis",
//   //   Country: "Russian Federation",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "56 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Scarlett Green",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "56 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Matthew Wilson",
//   //   Country: "Brazil",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "56 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Grace Martinez",
//   //   Country: "Australia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "57 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Benjamin Walker",
//   //   Country: "Germany",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "57 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Zoe Harris",
//   //   Country: "France",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "57 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Joshua Johnson",
//   //   Country: "Japan",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "58 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Sophie Lee",
//   //   Country: "South Africa",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "58 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Isaac Brown",
//   //   Country: "India",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "58 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Chloe Clark",
//   //   Country: "China",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "59 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Amelia Robinson",
//   //   Country: "United Kingdom",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "59 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Daniel Williams",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "59 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Isabella Lewis",
//   //   Country: "Saudi Arabia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "60 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Michael Smith",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "60 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Henry Garcia",
//   //   Country: "Russian Federation",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "60 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Samantha Wilson",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "61 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Ava Lee",
//   //   Country: "Brazil",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "61 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "William Clark",
//   //   Country: "Australia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "61 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Liam Wilson",
//   //   Country: "Germany",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "62 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Emma Thompson",
//   //   Country: "France",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "62 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "Michael Johnson",
//   //   Country: "Japan",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "62 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Scarlett Martinez",
//   //   Country: "South Africa",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "63 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Lucas Wilson",
//   //   Country: "India",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "63 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Oliver Brown",
//   //   Country: "China",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "63 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "Zoe Johnson",
//   //   Country: "United Kingdom",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "64 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "David Smith",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "64 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Amelia Taylor",
//   //   Country: "Saudi Arabia",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "64 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Nathan Johnson",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "65 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Lily Walker",
//   //   Country: "Russian Federation",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "65 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Sophia Martinez",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "65 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Henry Davis",
//   //   Country: "Brazil",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "66 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Chloe White",
//   //   Country: "Australia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "66 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Daniel Brown",
//   //   Country: "Germany",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "66 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Zoe Wilson",
//   //   Country: "France",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "67 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Matthew Martinez",
//   //   Country: "Japan",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "67 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Evelyn Johnson",
//   //   Country: "South Africa",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "67 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Chloe Young",
//   //   Country: "India",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "68 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Ethan Walker",
//   //   Country: "China",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "68 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Oliver Hall",
//   //   Country: "United Kingdom",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "68 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Market Place",
//   //   Name: "Ava Johnson",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "69 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Fresh Mart",
//   //   Name: "William Taylor",
//   //   Country: "Saudi Arabia",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "69 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Grocery Hub",
//   //   Name: "Sophia Martinez",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "69 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Quick Stop",
//   //   Name: "Zachary Johnson",
//   //   Country: "Russian Federation",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "70 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Budget Bazaar",
//   //   Name: "Emily Young",
//   //   Country: "Viet Nam",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "70 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Provisions",
//   //   Name: "James Martinez",
//   //   Country: "Brazil",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "70 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Affordable Market",
//   //   Name: "Lucas Robinson",
//   //   Country: "Australia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "71 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Daily Deals",
//   //   Name: "Sophia Williams",
//   //   Country: "Germany",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "71 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Super Saver",
//   //   Name: "Mia Lee",
//   //   Country: "France",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "71 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Top Choice Groceries",
//   //   Name: "Charlotte Davis",
//   //   Country: "Japan",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "72 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Essentials Plus",
//   //   Name: "Oliver Clark",
//   //   Country: "South Africa",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "72 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Deli Station Creations",
//   //   Name: "Lucas Walker",
//   //   Country: "India",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "72 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Blueberry天山翡翅",
//   //   Name: "Emily Brown",
//   //   Country: "China",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "73 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Long Biên",
//   //   Name: "Henry Young",
//   //   Country: "United Kingdom",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "73 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Conscious",
//   //   Name: "Amelia Robinson",
//   //   Country: "Viet Nam",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "73 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Everyday Savings",
//   //   Name: "Aiden Smith",
//   //   Country: "Saudi Arabia",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "74 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Smart Spender's",
//   //   Name: "Chloe Hall",
//   //   Country: "Iran (Islamic Republic of)",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "74 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Value Village",
//   //   Name: "Isabella Johnson",
//   //   Country: "Russian Federation",
//   //   Level: "Bronze",
//   //   Time: 1730376872,
//   //   Paid: "74 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Discount Darling",
//   //   Name: "Matthew Lewis",
//   //   Country: "Viet Nam",
//   //   Level: "Gold",
//   //   Time: 1730376872,
//   //   Paid: "75 hrs ago",
//   // },
//   // {
//   //   Store_Name: "Bargain Bonanza",
//   //   Name: "Mia Hall",
//   //   Country: "Brazil",
//   //   Level: "Silver",
//   //   Time: 1730376872,
//   //   Paid: "75 hrs ago",
//   // },
// ];

export const TransactionData = [
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Deli Station Creations",
    Name: "Robert Fox",
    Country: "Viet Nam",
    Level: "Bronze",
    Time: 1730376872,
    Paid: "5 mins ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Blueberry",
    Name: "Alice Smith",
    Country: "Viet Nam",
    Level: "Silver",
    Time: 1730265842,
    Paid: "10 mins ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Long Biên",
    Name: "John Doe",
    Country: "Israel",
    Level: "Bronze",
    Time: 1730372872,
    Paid: "15 mins ago",
    flag: "https://www.mrflag.com/wp-content/uploads/2018/11/Israel.png",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Everyday Savings",
    Name: "Sophie Reed",
    Country: "Russia",
    Level: "Gold",
    Time: 1730372872,
    Paid: "14 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/800px-Flag_of_Russia.svg.png?20120812153731",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Smart Spender's",
    Name: "Carter Lee",
    Country: "Viet Nam",
    Level: "Silver",
    Time: 1730375872,
    Paid: "14 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Value Village",
    Name: "Luna Hall",
    Country: "Brazil",
    Level: "Bronze",
    Time: 1730376472,
    Paid: "14 hrs ago",
    flag: "https://www.nationalflags.shop/WebRoot/vilkasfi01/Shops/2014080403/53E6/2F4E/F123/7D8D/CCB0/0A28/100B/04B4/Flag_of_Brazil.png",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Discount Darling",
    Name: "Eli Young",
    Country: "Australia",
    Level: "Gold",
    Time: 1730376870,
    Paid: "15 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1920px-Flag_of_Australia_%28converted%29.svg.png",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Bargain Bonanza",
    Name: "Ava Thompson",
    Country: "Germany",
    Level: "Silver",
    Time: 1730372362,
    Paid: "15 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/800px-Flag_of_Russia.svg.png?20120812153731",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Market Place",
    Name: "Andrew Scott",
    Country: "France",
    Level: "Bronze",
    Time: 1730372252,
    Paid: "15 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Fresh Mart",
    Name: "Ella Carter",
    Country: "Japan",
    Level: "Gold",
    Time: 1730372852,
    Paid: "16 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Grocery Hub",
    Name: "Zachary Campbell",
    Country: "South Africa",
    Level: "Silver",
    Time: 1730372352,
    Paid: "16 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Value Provisions",
    Name: "Daniel Lee",
    Country: "Brazil",
    Level: "Gold",
    Time: 1730376872,
    Paid: "24 hrs ago",
    flag: "https://www.nationalflags.shop/WebRoot/vilkasfi01/Shops/2014080403/53E6/2F4E/F123/7D8D/CCB0/0A28/100B/04B4/Flag_of_Brazil.png",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Affordable Market",
    Name: "Sophie Taylor",
    Country: "Australia",
    Level: "Silver",
    Time: 1730376872,
    Paid: "24 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1920px-Flag_of_Australia_%28converted%29.svg.png",
    Transaction_Mode: "Online",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Daily Deals",
    Name: "Elijah Moore",
    Country: "Germany",
    Level: "Bronze",
    Time: 1730376872,
    Paid: "24 hrs ago",
    flag: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/800px-Flag_of_Russia.svg.png?20120812153731",
    Transaction_Mode: "Offline",
  },
  {
    imgUrl:
      "https://img.freepik.com/free-photo/smiling-young-man-with-crossed-arms-outdoors_1140-255.jpg",
    Store_Name: "Mega Mart",
    Name: "Mason Green",
    Country: "USA",
    Level: "Gold",
    Time: 1730376872,
    Paid: "1 day ago",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
    Transaction_Mode: "Online",
  },
];

export const TaskData = [
  {
    completed: false,
    title: "Follow Up with Prospective Client",
    dueDate: "2024-11-10",
    createdDate: "2024-11-01T12:09:31.336Z", // Today with time
    description:
      "Reach out to the prospective client who showed interest in our product during the last webinar.",
  },
  {
    completed: true,
    title: "Update CRM with New Leads",
    dueDate: "2024-11-05",
    createdDate: "2024-11-01T10:09:31.336Z", // Today with time
    description:
      "Ensure all new leads from last week’s conference are entered into the CRM and assigned to sales reps.",
  },
  {
    completed: true,
    title: "Prepare Sales Report",
    dueDate: "2024-11-15",
    createdDate: "2024-10-31T13:09:31.336Z", // Yesterday with time
    description:
      "Compile and analyze sales data from the last quarter to present to the management team.",
  },
  {
    completed: false,
    title: "Plan Quarterly Sales Strategy",
    dueDate: "2024-11-20",
    createdDate: "2024-10-31T07:10:21.336Z", // Yesterday with time
    description:
      "Develop a comprehensive strategy for the upcoming quarter to improve sales and increase market reach.",
  },
  {
    completed: true,
    title: "Conduct Product Demo",
    dueDate: "2024-11-12",
    createdDate: "2024-10-30T13:09:31.336Z", // Day before yesterday with time
    description:
      "Schedule and conduct a live demo of the product for potential clients in the healthcare sector.",
  },
  {
    completed: true,
    title: "Attend Networking Event",
    dueDate: "2024-11-08",
    createdDate: "2024-10-31T11:09:31.336Z", // Day before yesterday with time
    description:
      "Participate in the local networking event to connect with potential clients and industry partners.",
  },
];
